[package]
name = "ghostdag"
version = "1.13.5"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
starcoin-consensus.workspace = true
starcoin-crypto.workspace = true
starcoin-types.workspace = true
serde.workspace = true
itertools.workspace = true
parking_lot.workspace = true
rocksdb.workspace = true
reachability.workspace = true