[package]
name = "dag-consensus"
version = "1.13.5"
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ghostdag.workspace = true
reachability.workspace = true
dag-database.workspace = true
parking_lot.workspace = true
starcoin-crypto.workspace = true
starcoin-types.workspace = true
anyhow.workspace = true